django/bbs/urls.py
from django.conf.urls import include, url

from . import views


app_name = 'bbs'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^forum/(?P<forum_id>[0-9]+)/$', views.forum),
    url(r'^forum/(?P<forum_id>[0-9]+)/(?P<page>[0-9]+)/$',
        views.forum, name='forum'),
    url(r'^forum/(?P<forum_id>[0-9]+)/new/$', views.new_post, name='new_post'),
    url(r'^p/(?P<post_id>[0-9]+)/$', views.post),
    url(r'^p/(?P<post_id>[0-9]+)/(?P<page>[0-9]+)/$',
        views.post, name='post'),
    url(r'^p/(?P<post_id>[0-9]+)/del/$', views.del_post, name='del_post'),
    url(r'^r/(?P<reply_id>[0-9]+)/del/$', views.del_reply, name='del_reply'),
    url(r'^p/(?P<post_id>[0-9]+)/top/(?P<top>[0-9]+)/$',
        views.top_post, name='top_post'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^user/$', views.user, name='user'),
]

django/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^bbs/', include('bbs.urls')),
    url(r'^admin/', admin.site.urls),
]

django/bbs/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Client(models.Model):
    username = models.CharField(max_length=20)
    password = models.CharField('sha1 of original password', max_length=40)

    def __str__(self):
        return "Client: %s" % self.username


class User(models.Model):
    client = models.OneToOneField(
        Client,
        on_delete=models.CASCADE,
        primary_key=True,
        verbose_name='related client',
    )
    name = models.CharField('nickname', max_length=20)
    email = models.EmailField(null=True)

    def __str__(self):
        return "User: %s" % self.name


class Section(models.Model):
    name = models.CharField(max_length=50)
    admins = models.ManyToManyField(User)

    def __str__(self):
        return "Section: %s" % self.name


class Forum(models.Model):
    section = models.ForeignKey(Section, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    admins = models.ManyToManyField(User)

    def __str__(self):
        return "Forum: %s" % self.name

    def post_count(self):
        return self.post_set.count()

    def reply_and_post_count(self):
        return self.reply_set.count()+self.post_set.count()

    def reply_and_post_count_today(self):
        import datetime
        today = datetime.date.today()
        r = self.reply_set.filter(update__gte=today).count()
        p = self.post_set.filter(update__gte=today).count()
        return r+p

    def page_max(self):
        p = self.post_set.count()
        pages = (p-1)//20+1
        if p == 0:
            pages = 1
        return pages


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField('date published')
    update = models.DateTimeField("last edit's date")
    topic = models.CharField(max_length=30)
    text = models.CharField(max_length=500,blank=True,null=True)
    forum = models.ForeignKey(Forum, on_delete=models.CASCADE)
    top = models.IntegerField('priority', default=0)
    newdate = models.DateTimeField("last reply's date")

    def __str__(self):
        return "Post: %s [by %s]" % (self.topic, self.author.name)

    class Meta:
        ordering = ['-top', '-newdate']

    def delete(self, *args, **kwargs):
        import os
        for pfile in self.pfile_set.all():
            try:
                os.remove('/var/www/upload/'+pfile.name)
            except OSError:
                pass
        for r in self.reply_set.all():
            for rfile in r.rfile_set.all():
                try:
                    os.remove('/var/www/upload/'+rfile.name)
                except OSError:
                    pass
        super(Post, self).delete(*args, **kwargs)

    def last_reply_author(self):
        c = self.reply_set.count()
        if c==0:
            return self.author.name
        return self.reply_set.all()[c-1].author.name

    def page_max(self):
        p = self.reply_set.count()
        pages = (p-1)//20+1
        if p == 0:
            pages = 1
        return pages

    def previous(self):
        p = Post.objects.filter(newdate__gt=self.newdate).order_by('-newdate').last()
        return p

    def next(self):
        n = Post.objects.filter(newdate__lt=self.newdate).order_by('-newdate').first()
        return n

    def admin(self, username):
        if User.objects.filter(name=username).count() == 0:
            return False
        u = User.objects.get(name=username)
        if u in self.forum.admins.all():
            return True
        if u in self.forum.section.admins.all():
            return True
        return False


class Reply(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField('date published')
    update = models.DateTimeField("last edit's date")
    text = models.CharField(max_length=500,blank=True,null=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    forum = models.ForeignKey(Forum, on_delete=models.CASCADE)

    def __str__(self):
        return "Reply: %s [by %s]" % (self.text, self.author.name)

    class Meta:
        ordering = ['date']

    def save(self, *args, **kwargs):
        super(Reply, self).save(*args, **kwargs)
        self.post.newdate = self.update
        self.post.save()

    def delete(self, *args, **kwargs):
        import os
        for rfile in self.rfile_set.all():
            try:
                os.remove('/var/www/upload/'+rfile.name)
            except OSError:
                pass
        super(Reply, self).delete(*args, **kwargs)


class PFile(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)


class RFile(models.Model):
    reply = models.ForeignKey(Reply, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)

django/bbs/forms.py
# coding=utf8
from django import forms
from django.core.exceptions import ValidationError

from .models import Client, User


class ReplyForm(forms.Form):
    text = forms.CharField(
        label='正文',
        widget=forms.Textarea(attrs={
            'class': 'form-control',
            'placeholder': '正文',
            }),
        min_length=4,
        max_length=500,
        error_messages={
            'required': '正文不能为空',
            'min_length': '正文长度为4-500字符',
            'max_length': '正文长度为4-500字符',
        })


class New_PostForm(forms.Form):
    topic = forms.CharField(
        label='主题',
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': '主题',
            }),
        min_length=4,
        max_length=30,
        error_messages={
            'required': '主题不能为空',
            'min_length': '主题长度为4-30字符',
            'max_length': '主题长度为4-30字符',
        })
    text = forms.CharField(
        label='正文',
        widget=forms.Textarea(attrs={
            'class': 'form-control',
            'placeholder': '正文',
            }),
        min_length=4,
        max_length=500,
        error_messages={
            'required': '正文不能为空',
            'min_length': '正文长度为4-500字符',
            'max_length': '正文长度为4-500字符',
        })
    files = forms.FileField(
        label='附件',
        required=False,
        widget=forms.ClearableFileInput(attrs={
            'multiple': True
        }))


def validate_username_exist(value):
    if Client.objects.filter(username=value).count() > 0:
        raise ValidationError(
            '用户名%(value)s已存在',
            params={'value': value},
        )
def validate_nickname_exist(value):
    if User.objects.filter(name=value).count() > 0:
        raise ValidationError(
            '昵称%(value)s已存在',
            params={'value': value},
        )

class RegisterForm(forms.Form):
    username = forms.CharField(
        label='用户',
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': '用户名',
            }),
        min_length=4,
        max_length=20,
        validators=[validate_username_exist],
        error_messages={
            'required': '用户名不能为空',
            'min_length': '用户名长度为4-20字符',
            'max_length': '用户名长度为4-20字符',
        })
    password = forms.CharField(
        label='密码',
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': '密码',
            }),
        min_length=6,
        error_messages={
            'required': '密码不能为空',
            'min_length': '密码长度为6-20字符',
        })
    nickname = forms.CharField(
        label='昵称',
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': '昵称',
            }),
        min_length=4,
        max_length=20,
        validators=[validate_nickname_exist],
        error_messages={
            'required': '昵称不能为空',
            'min_length': '昵称长度为4-20字符',
            'max_length': '昵称长度为4-20字符',
        })

django/bbs/views.py
# coding=utf8
import sys
reload(sys)
sys.setdefaultencoding('utf8')

from django.shortcuts import render, redirect, get_object_or_404
import hashlib, string

from .models import Client, User, Section, Forum, Post, Reply, PFile


def index(request):
    return render(request, 'bbs/index.html', {'sections': Section.objects})


def forum(request, forum_id="0", page="1"):
    f = get_object_or_404(Forum, pk=string.atoi(forum_id))
    p = string.atoi(page)
    return render(request, 'bbs/forum.html', {
        'forum': f, 'page': p, 'posts': f.post_set.all()[(p-1)*20:p*20]
        })


from .forms import New_PostForm
def new_post(request, forum_id="0"):
    if not request.session.has_key('bbsname'):
        return redirect('bbs:login')
    f = get_object_or_404(Forum, pk=string.atoi(forum_id))
    if request.method == 'POST':
        form = New_PostForm(request.POST, request.FILES)
        if form.is_valid():
            to = form.cleaned_data['topic']
            te = form.cleaned_data['text']
            u = get_object_or_404(User, name=request.session['bbsname'])
            import datetime
            n = datetime.datetime.now()
            p = Post(author=u, date=n, update=n, topic=to, text=te, forum=f, newdate=n)
            p.save()
            files = request.FILES.getlist('files')
            for fi in files:
                filename = 'p'+str(p.id)+'-'+fi.name
                with open('/var/www/upload/'+filename, 'wb+') as destination:
                    for chunk in fi.chunks():
                        destination.write(chunk)
                pfile = PFile(post=p, name=filename)
                pfile.save()
            return redirect('bbs:post', p.id, 1)
    else:
        form = New_PostForm()
    return render(request, 'bbs/new_post.html', {'forum': f, 'form': form})


from .forms import ReplyForm
def post(request, post_id="0", page="1"):
    po = get_object_or_404(Post, pk=string.atoi(post_id))
    pa = string.atoi(page)
    if request.method == 'POST':
        form = ReplyForm(request.POST)
        if form.is_valid():
            t = form.cleaned_data['text']
            u = get_object_or_404(User, name=request.session['bbsname'])
            import datetime
            n = datetime.datetime.now()
            r = Reply(author=u, date=n, update=n, text=t, post=po, forum=po.forum)
            r.save()
            return redirect('bbs:post', po.id, po.page_max())
    else:
        form = ReplyForm()
    admin = False
    if request.session.has_key('bbsname'):
        if po.admin(request.session['bbsname']):
            admin = True
    return render(request, 'bbs/post.html', {
        'post': po, 'page': pa, 'form': form, 'floor': (pa-1)*20+1,
        'admin': admin,
        'replies': po.reply_set.all()[(pa-1)*20:pa*20]
        })


def del_post(request, post_id="0"):
    p = get_object_or_404(Post, pk=string.atoi(post_id))

    if not request.session.has_key('bbsname'):
        return redirect('bbs:login')
    u = get_object_or_404(User, name=request.session['bbsname'])
    if u!=p.author and not p.admin(request.session['bbsname']):
        context = {'message': '无权限进行此操作！'}
        return render(request, 'bbs/system_message.html', context)

    p.delete()
    return redirect('bbs:forum', p.forum.id, 1)


def del_reply(request, reply_id="0"):
    r = get_object_or_404(Reply, pk=string.atoi(reply_id))

    if not request.session.has_key('bbsname'):
        return redirect('bbs:login')
    u = get_object_or_404(User, name=request.session['bbsname'])
    if u!=r.author and not r.post.admin(request.session['bbsname']):
        context = {'message': '无权限进行此操作！'}
        return render(request, 'bbs/system_message.html', context)

    r.delete()
    return redirect('bbs:post', r.post.id, 1)


def top_post(request, post_id="0", top="0"):
    p = get_object_or_404(Post, pk=string.atoi(post_id))

    if not request.session.has_key('bbsname'):
        return redirect('bbs:login')
    if not p.admin(request.session['bbsname']):
        context = {'message': '无权限进行此操作！'}
        return render(request, 'bbs/system_message.html', context)

    p.top = string.atoi(top)
    p.save()
    return redirect('bbs:forum', p.forum.id, 1)


def login(request):
    if request.session.has_key('bbsname'):
        context = {'message': request.session['bbsname'] +
            ': 您已登录！'}
        return render(request, 'bbs/system_message.html', context)
    e = ''
    if request.method == 'POST':
        u = request.POST['username']
        p = request.POST['password']
        from django.core.exceptions import ObjectDoesNotExist
        try:
            c = Client.objects.get(username=u)
            if c.password == hashlib.sha1(p).hexdigest():
                request.session.flush()
                request.session['bbsname'] = c.user.name
                return render(request, 'bbs/index.html', {'sections': Section.objects})
            e += '密码错误！'
        except ObjectDoesNotExist:
            e += '用户不存在！'
    return render(request, 'bbs/login.html', {'error_message': e})


def logout(request):
    try:
        del request.session['bbsname']
    except KeyError:
        pass
    request.session.flush()
    return render(request, 'bbs/index.html', {'sections': Section.objects})


from .forms import RegisterForm
def register(request):
    if request.session.has_key('bbsname'):
        context = {'message': request.session['bbsname'] +
            ': 您已登录！'}
        return render(request, 'bbs/system_message.html', context)
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            u = form.cleaned_data['username']
            p = form.cleaned_data['password']
            n = form.cleaned_data['nickname']
            c = Client(username=u, password=hashlib.sha1(p).hexdigest())
            c.save()
            User.objects.create(client=c, name=n)
            request.session.flush()
            request.session['bbsname'] = n
            return render(request, 'bbs/index.html', {'sections': Section.objects})
    else:
        form = RegisterForm()
    return render(request, 'bbs/register.html', {'form': form})


def user(request):
    pass

django/bbs/templates/bbs/forum.html
{% include 'bbs/meta_head.html' %}
{% include 'bbs/meta_header.html' %}
<div class="container">

<div class="page-header">
  <hr>
  <h4><a href="{% url 'bbs:index' %}">论坛</a>>>{{ forum.section.name }}>>{{ forum.name }}</h4>
  <a class="btn btn-small btn-primary" href="{% url 'bbs:new_post' forum.id %}" role="button">发帖</a>
  {% ifequal page 1 %}
    上一页
  {% else %}
    <a href="{% url 'bbs:forum' forum.id page|add:-1 %}">上一页</a>
  {% endifequal %}
  {{ page }}/{{ forum.page_max }}
  {% ifequal page forum.page_max %}
    下一页
  {% else %}
    <a href="{% url 'bbs:forum' forum.id page|add:1 %}">下一页</a>
  {% endifequal %}
</div>

<table class="table table-hover">
<thead>
  <tr>
    <th width=60%>主题</th>
    <th width=17%>作者/日期</th>
    <th width=8%>回复</th>
    <th width=15%>最后发表</th>
  </tr>
</thead>
{% for post in posts %}
<tr>
    <td><a href="{% url 'bbs:post' post.id 1 %}">
      {% ifequal post.top 0 %}
        {{ post.topic }}
      {% else %}
        【&uArr;】<strong>{{ post.topic }}</strong>
      {% endifequal %}
      </a></td>
    <td>{{ post.author.name }}
      <span class="text-muted small">{{ post.date|date:"Y-n-j" }}</span></td>
    <td>{{ post.reply_set.count }}</td>
    <td>{{ post.last_reply_author }}</td>
</tr>
{% endfor %}
</table>

</div>
{% include 'bbs/meta_footer.html' %}

django/bbs/templates/bbs/index.html
{% include 'bbs/meta_head.html' %}
{% include 'bbs/meta_header.html' %}
<div class="container">

{% for sec in sections.all %}
<div class="jumbotron">
    <h2>{{ sec.name }}</h2>
    <span class="text-muted">
    分区版主:
    {% for admin in sec.admins.all %}
        {{ admin.name }}
    {% endfor %}
    </span>

    {% for forum in sec.forum_set.all %}
        <h4><a href="{% url 'bbs:forum' forum.id 1 %}">【{{ forum.name }}】</a>
        <small>
        新帖:{{ forum.reply_and_post_count_today }}
        主题:{{ forum.post_count }}
        帖数:{{ forum.reply_and_post_count }}
        </small>
        </h4>
    {% endfor %}
</div>
{% endfor %}

</div>
{% include 'bbs/meta_footer.html' %}

django/bbs/templates/bbs/login.html
{% include 'bbs/meta_head.html' %}
<link rel="stylesheet" href="/static/bbs/login.css">
{% include 'bbs/meta_header.html' %}


<form action="{% url 'bbs:login' %}" method="post" class="form-signin">
{% csrf_token %}
  <br /><br />
  <h2 class="form-signin-heading">请登录</h2>
<input type="text" name="username" class="form-control" placeholder="用户名" required autofocus>
<input type="password" name="password" class="form-control" placeholder="密码" required>
{% if error_message %}<strong>{{ error_message }}</strong>{% endif %}
<button class="btn btn-lg btn-primary btn-block" type="submit">登录</button>
<a href="{% url 'bbs:register' %}">注册</a>
</form>

{% include 'bbs/meta_footer.html' %}

django/bbs/templates/bbs/meta_footer.html
<footer class="footer">
  <div class="container">
      <p class="text-muted" align="center"><a href="mailto:chenq182@sina.com">陈诠</a>作品</p>
  </div>
</footer>

<script src="//cdn.bootcss.com/jquery/1.11.3/jquery.min.js"></script>
<script src="//cdn.bootcss.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</body>
</html>

django/bbs/templates/bbs/meta_head.html
<!DOCTYPE html>
<html>
<head>
<title>论坛</title>
  <meta charset="utf-8">
  <link rel="stylesheet" href="//cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link rel="stylesheet" href="/static/bbs/footer.css"><!--footer-->

django/bbs/templates/bbs/meta_header.html
</head>
<body>
<!-- Fixed navbar -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">陈诠的个人主站</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><a href="/">主页</a></li>
        <li><a href="/about">关于</a></li>
        <li><a href="/email">邮箱</a></li>
        <li class="active dropdown">
          <a href="/bbs" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">论坛 <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/bbs">首页</a></li>
            <li role="separator" class="divider"></li>
            <li class="dropdown-header">管理</li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
{% if request.session.bbsname %}
        <li class="active"><a href="{% url 'bbs:user' %}">{{ request.session.bbsname }}</a></li>
        <li><a href="{% url 'bbs:logout' %}">注销</a></li>
{% else %}
        <li class="active"><a href="{% url 'bbs:login' %}">登录</a></li>
        <li><a href="{% url 'bbs:register' %}">注册</a></li>
{% endif %}
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

django/bbs/templates/bbs/new_post.html
{% include 'bbs/meta_head.html' %}
{% include 'bbs/meta_header.html' %}
<div class="container">

<div class="page-header">
  <hr>
  <h4><a href="{% url 'bbs:index' %}">论坛</a>
    >>{{ forum.section.name }}>>
    <a href="{% url 'bbs:forum' forum.id 1 %}">{{ forum.name }}</a>
    >>发表帖子</h4>
</div>

<form enctype="multipart/form-data" action="{% url 'bbs:new_post' forum.id %}" method="post" class="form-horizontal">
{% csrf_token %}
{% for field in form %}
  <div class="form-group">
    <span class="col-sm-2 control-label">{{ field.label }}</span>
    <div class="col-sm-8">{{ field }}</div>
    <div class="col-sm-offset-2">{{ field.errors }}</div>
  </div>
{% endfor %}
<div class="form-group">
  <div class="col-sm-offset-2 col-sm-10">
    <button class="btn btn-default" type="submit">发表帖子</button>
    <button class="btn btn-default" type="reset">清空</button>
  </div>
</div>
</form>

</div>
{% include 'bbs/meta_footer.html' %}

django/bbs/templates/bbs/post.html
{% include 'bbs/meta_head.html' %}
{% include 'bbs/meta_header.html' %}
<div class="container">

<div class="page-header">
  <hr>
  <h4><a href="{% url 'bbs:index' %}">论坛</a>
    >>{{ post.forum.section.name }}>>
    <a href="{% url 'bbs:forum' post.forum.id 1 %}">{{ post.forum.name }}</a>
    >>{{ post.topic }}</h4>

  {% if post.previous %}
    <a href="{% url 'bbs:post' post.previous.id 1 %}">上一主题</a>
  {% else %}
    上一主题
  {% endif %}

  {% ifequal page 1 %}
    上一页
  {% else %}
    <a href="{% url 'bbs:post' post.id page|add:-1 %}">上一页</a>
  {% endifequal %}
  {{ page }}/{{ post.page_max }}
  {% ifequal page post.page_max %}
    下一页
  {% else %}
    <a href="{% url 'bbs:post' post.id page|add:1 %}">下一页</a>
  {% endifequal %}

  {% if post.next %}
    <a href="{% url 'bbs:post' post.next.id 1 %}">下一主题</a>
  {% else %}
    下一主题
  {% endif %}
</div>


<table class="table table-bordered table-striped">
  <tr>
    <th width=180px></th>
    <th>{{ post.topic }}</th>
    <th width=8%><a class="btn btn-default" href="#reply" role="button">回复</a></th>
  </tr>

{% ifequal page 1 %}
  <tr>
    <td rowspan="2" align="center">
      <img src="/static/bbs/default_portrait.jpeg" class="img-rounded" width="130px" height="130px">
      <br />{{ post.author.name }}
    </td>
    <td colspan="2">{{ post.text|linebreaksbr }}
    {% ifequal post.pfile_set.count 0 %}
    {% else %}
        <hr style="margin:2px;margin-top:10px">附件:<br />
    {% endifequal %}
    {% for file in post.pfile_set.all %}
        <a href="/upload/{{ file.name }}">{{ file.name }}</a><br />
    {% endfor %}
    </td>
  </tr>
  <tr height=30px>
    <td colspan="2" class="text-muted" align="right">
      {% if admin %}
        {% ifequal post.top 0 %}
          <a href="{% url 'bbs:top_post' post.id 1 %}">置顶</a>
        {% else %}
          <a href="{% url 'bbs:top_post' post.id 0 %}">取消置顶</a>
        {% endifequal %}
        <a href="{% url 'bbs:del_post' post.id %}">删除</a>
      {% else %}
        {% ifequal request.session.bbsname post.author.name %}
          <a href="{% url 'bbs:del_post' post.id %}">删除</a>
        {% endifequal %}
      {% endif %}
      1楼 {{ post.date|date:"Y-n-j H:i:s" }}
    </td>
  </tr>
{% endifequal %}

{% for reply in replies %}
  <tr>
    <td rowspan="2" align="center">
      <img src="/static/bbs/default_portrait.jpeg" class="img-rounded" width="130px" height="130px">
      <br />{{ reply.author.name }}
    </td>
    <td colspan="2">{{ reply.text|linebreaksbr }}</td>
  </tr>
  <tr height=30px>
    <td colspan="2" class="text-muted" align="right">
      {% if admin %}
        <a href="{% url 'bbs:del_reply' reply.id %}">删除</a>
      {% else %}
        {% ifequal request.session.bbsname reply.author.name %}
          <a href="{% url 'bbs:del_reply' reply.id %}">删除</a>
        {% endifequal %}
      {% endif %}
      {{ forloop.counter|add:floor }}楼 {{ reply.date|date:"Y-n-j H:i:s" }}
    </td>
  </tr>
{% endfor %}

</table>


{% if request.session.bbsname %}
<form action="{% url 'bbs:post' post.id 1 %}" method="post" class="form-horizontal">
{% csrf_token %}
<div class="col-sm-offset-2"><a name="reply"><h4><strong>发表回复</strong></h4></a></div>
{% for field in form %}
  <div class="form-group">
    <span class="col-sm-2 control-label">{{ field.label }}</span>
    <div class="col-sm-8">{{ field }}</div>
    <div class="col-sm-offset-2">{{ field.errors }}</div>
  </div>
{% endfor %}
<div class="form-group">
  <div class="col-sm-offset-2 col-sm-10">
    <button class="btn btn-default" type="submit">发表回复</button>
    <button class="btn btn-default" type="reset">清空</button>
  </div>
</div>
</form>
{% endif %}


</div>
{% include 'bbs/meta_footer.html' %}

django/bbs/templates/bbs/register.html
{% include 'bbs/meta_head.html' %}
<link rel="stylesheet" href="/static/bbs/login.css">
{% include 'bbs/meta_header.html' %}


<form action="{% url 'bbs:register' %}" method="post" class="form-signin">
{% csrf_token %}
  <br /><br />
  <h2 class="form-signin-heading">请注册</h2>
{% for field in form %}
    <!--{{ field.label }}-->
    {{ field }}
    {{ field.errors }}
{% endfor %}
<button class="btn btn-lg btn-primary btn-block" type="submit">注册</button>
<a href="{% url 'bbs:login' %}">已有账号?</a>
</form>

{% include 'bbs/meta_footer.html' %}

django/bbs/templates/bbs/system_message.html
{% load staticfiles %}

<style type="text/css">
    html * { padding:0; margin:0; }
    body * { padding:10px 20px; }
    body * * { padding:0; }
    body { font:small sans-serif; background:#eee; }
    body>div { border-bottom:1px solid #ddd; }
    h1 { font-weight:normal; margin-bottom:.4em; }
    h1 span { font-size:60%; color:#666; font-weight:normal; }
    table { border:none; border-collapse: collapse; width:100%; }
    td, th { vertical-align:top; padding:2px 3px; }
    th { width:12em; text-align:right; color:#666; padding-right:.5em; }
    #info { background:#f6f6f6; }
    #info ol { margin: 0.5em 4em; }
    #info ol li { font-family: monospace; }
    #summary { background: #ffc; }
    #explanation { background:#eee; border-bottom: 0px none; }
</style>

<div id="summary">
<h1>{{ message }}</h1>
<div>